"""Access to the frozen fixture corpus and its ground-truth sidecars.

The corpus contract:

- Fixtures live under `tests/paper/fixtures/<provenance-bucket>/`.
- Every fixture's SHA-256 is pinned in `fixtures/MANIFEST.sha256`; a hash mismatch is a test
  failure. Fixtures are never regenerated by code under test.
- Every fixture has exactly one sidecar: `<fixture-stem>.json` beside it, in the pinned schema.
- A fixture is corrupt-by-construction (negative tests only) iff any of its sidecar `features`
  starts with `"corrupt"`.
"""

from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"
MANIFEST_PATH = FIXTURES_DIR / "MANIFEST.sha256"

#: Provenance buckets, in canonical order. Directories exist as they are populated.
BUCKETS = (
    "office_authored",
    "google_export",
    "libreoffice_export",
    "other_producers",
    "self_generated",
)

_SIDECAR_TOP_LEVEL_KEYS = (
    "fixture", "provenance", "features", "ground_truth", "verified_by", "date"
)
_PROVENANCE_KEYS = ("app", "version", "notes")
_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def iter_fixture_relpaths() -> List[str]:
    """Return sorted bucket-relative POSIX paths of every `.pptx` under the corpus."""
    return sorted(
        p.relative_to(FIXTURES_DIR).as_posix()
        for p in FIXTURES_DIR.rglob("*.pptx")
        if p.parent != FIXTURES_DIR  # -- fixtures must live inside a bucket directory
    )


def iter_manifest_relpaths() -> List[str]:
    """Return every fixture binary and sidecar path covered by the frozen manifest."""
    return sorted(
        p.relative_to(FIXTURES_DIR).as_posix()
        for suffix in ("*.pptx", "*.json")
        for p in FIXTURES_DIR.rglob(suffix)
        if p.parent != FIXTURES_DIR
    )


def fixture_path(relpath: str) -> Path:
    """Return the absolute path of the fixture at bucket-relative `relpath`."""
    return FIXTURES_DIR / relpath


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def manifest_entries(manifest_text: "Optional[str]" = None) -> Dict[str, str]:
    """Return {bucket-relative-path: sha256-hex} parsed from MANIFEST.sha256.

    Raises ValueError on a duplicated relpath: silent last-line-wins would let a stale hash
    line sit in the manifest looking enforced while a contradictory one actually governs.
    """
    if manifest_text is None:
        manifest_text = MANIFEST_PATH.read_text(encoding="utf-8")
    entries: Dict[str, str] = {}
    for line in manifest_text.splitlines():
        line = line.strip()
        if not line:
            continue
        digest, _, relpath = line.partition("  ")
        if relpath in entries:
            raise ValueError("MANIFEST.sha256 lists %r more than once" % relpath)
        entries[relpath] = digest
    return entries


def sidecar_path(relpath: str) -> Path:
    return fixture_path(relpath).with_suffix(".json")


def load_sidecar(relpath: str) -> dict:
    return json.loads(sidecar_path(relpath).read_text(encoding="utf-8"))


def is_corrupt_fixture(relpath: str) -> bool:
    """True for corrupt-by-construction fixtures, which are negative-test-only."""
    return any(str(f).startswith("corrupt") for f in load_sidecar(relpath)["features"])


def sidecar_schema_problems(doc: object, relpath: str) -> List[str]:
    """Return a list of pinned-schema violations for sidecar `doc` (empty when valid)."""
    problems = []
    if not isinstance(doc, dict):
        return ["sidecar is not a JSON object"]
    if sorted(doc.keys()) != sorted(_SIDECAR_TOP_LEVEL_KEYS):
        problems.append(
            "top-level keys %r != pinned %r" % (sorted(doc.keys()), sorted(_SIDECAR_TOP_LEVEL_KEYS))
        )
        return problems
    if doc["fixture"] != Path(relpath).name:
        problems.append("'fixture' %r != actual filename %r" % (doc["fixture"], Path(relpath).name))
    provenance = doc["provenance"]
    if not isinstance(provenance, dict) or sorted(provenance.keys()) != sorted(_PROVENANCE_KEYS):
        problems.append("'provenance' keys != pinned %r" % (_PROVENANCE_KEYS,))
    else:
        for key in _PROVENANCE_KEYS:
            if not (isinstance(provenance[key], str) and provenance[key].strip()):
                problems.append("'provenance.%s' must be a non-empty string" % key)
    features = doc["features"]
    if not (
        isinstance(features, list)
        and features
        and all(isinstance(f, str) and f.strip() for f in features)
    ):
        problems.append("'features' must be a non-empty list of non-empty strings")
    if not (isinstance(doc["ground_truth"], dict) and doc["ground_truth"]):
        problems.append("'ground_truth' must be a non-empty object")
    if not (isinstance(doc["verified_by"], str) and doc["verified_by"].strip()):
        problems.append("'verified_by' must be a non-empty string")
    if not (isinstance(doc["date"], str) and _is_real_date(doc["date"])):
        problems.append("'date' must be a real YYYY-MM-DD calendar date")
    return problems


def _is_real_date(value: str) -> bool:
    """True only for a well-formed AND calendar-valid YYYY-MM-DD date."""
    if not _DATE_RE.fullmatch(value):
        return False
    try:
        datetime.strptime(value, "%Y-%m-%d")
    except ValueError:
        return False
    return True
